compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-04-05"

[vars]
USE_RELOADLY_SANDBOX = true
RELOADLY_API_CLIENT_ID = ""
RELOADLY_API_CLIENT_SECRET = ""
ADDRESS_PERMIT2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
ADDRESS_GIFT_CARD_TREASURY = ""
